# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/User/Music/final_project2.0/NP_Final/.Xil/Vivado-13672-SukithanTDell/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.cache/wt [current_project]
set_property parent.project_path C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/sources_1/new/Add_Sub.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/Project/3bit_Add/3bit_Add.srcs/sources_1/new/Adder_3bit.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/Project/ProgramCounter/ProgramCounter.srcs/sources_1/imports/new/D_FF.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/Project/Registers/Registers.srcs/sources_1/imports/new/Decoder_2_to_4.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/Project/Registers/Registers.srcs/sources_1/imports/new/Decoder_3_to_8.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/sources_1/imports/new/FA.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/sources_1/imports/new/HA.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/new/Instruction_Decoder.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/new/LUT_16_7.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/Project/Multiplexer/Multiplexer.srcs/sources_1/new/Mux_2_to_1_3bit.sv
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/Project/Multiplexer/Multiplexer.srcs/sources_1/new/Mux_2_to_1_4bit.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/Project/Multiplexer/Multiplexer.srcs/sources_1/new/Mux_8_to_1_4bit.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/new/PC.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/Project/Program_ROM/Program_ROM.srcs/sources_1/new/Program_ROM.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/sources_1/imports/new/RCA.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/Project/Registers/Registers.srcs/sources_1/new/Register_4bit.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/Project/Registers/Registers.srcs/sources_1/new/Register_Bank.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/new/Slow_Clk.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/new/multiplier_2.vhd
  C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/sources_1/imports/Desktop/NanoProcessor.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/constrs_1/imports/Lab/Basys3Labs.xdc
set_property used_in_implementation false [get_files C:/Users/User/Music/final_project2.0/NP_Final/NP_Fnal.srcs/constrs_1/imports/Lab/Basys3Labs.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top NanoProcessor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NanoProcessor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NanoProcessor_utilization_synth.rpt -pb NanoProcessor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
